web:
  build: .
  command: bundle exec thin start
  ports:
    - 80:3000
  volumes:
    - .:/app
  links:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
redis:
  image: redis:latest
